LangString addOrReinstall ${LANG_HEBREW} "הוספה או התקנה מחדש של רכיבים"
LangString alreadyInstalled ${LANG_HEBREW} "כבר מותקן"
LangString alreadyInstalledLong ${LANG_HEBREW} "${PRODUCTNAME} ${VERSION} כבר מותקן. בחרו את הפעולה הרצויה ולחצו על הבא כדי להמשיך."
LangString appRunning ${LANG_HEBREW} "{{product_name}} פועל כרגע! יש לסגור אותו ולנסות שוב."
LangString appRunningOkKill ${LANG_HEBREW} "{{product_name}} פועל כרגע!$\nלחצו על אישור כדי לסגור אותו"
LangString chooseMaintenanceOption ${LANG_HEBREW} "בחרו את פעולת התחזוקה לביצוע."
LangString choowHowToInstall ${LANG_HEBREW} "בחרו איך להתקין את ${PRODUCTNAME}."
LangString createDesktop ${LANG_HEBREW} "יצירת קיצור דרך בשולחן העבודה"
LangString dontUninstall ${LANG_HEBREW} "לא להסיר"
LangString dontUninstallDowngrade ${LANG_HEBREW} "לא להסיר (התקנת גרסה ישנה יותר בלי הסרה אינה אפשרית במתקין זה)"
LangString failedToKillApp ${LANG_HEBREW} "לא ניתן היה לסגור את {{product_name}}. יש לסגור אותו ולנסות שוב"
LangString installingWebview2 ${LANG_HEBREW} "מתקין את WebView2..."
LangString newerVersionInstalled ${LANG_HEBREW} "גרסה חדשה יותר של ${PRODUCTNAME} כבר מותקנת! לא מומלץ להתקין גרסה ישנה יותר. אם בכל זאת רוצים, עדיף להסיר קודם את הגרסה הנוכחית. בחרו את הפעולה הרצויה ולחצו על הבא כדי להמשיך."
LangString older ${LANG_HEBREW} "ישנה יותר"
LangString olderOrUnknownVersionInstalled ${LANG_HEBREW} "גרסה $R4 של ${PRODUCTNAME} מותקנת במחשב. מומלץ להסיר את הגרסה הנוכחית לפני ההתקנה. בחרו את הפעולה הרצויה ולחצו על הבא כדי להמשיך."
LangString silentDowngrades ${LANG_HEBREW} "התקנת גרסה ישנה יותר אינה אפשרית במתקין זה, ולכן ההתקנה השקטה לא יכולה להמשיך. יש להשתמש במתקין הרגיל.$\n"
LangString unableToUninstall ${LANG_HEBREW} "ההסרה נכשלה!"
LangString uninstallApp ${LANG_HEBREW} "הסרת ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_HEBREW} "הסרה לפני ההתקנה"
LangString unknown ${LANG_HEBREW} "לא ידועה"
LangString webview2AbortError ${LANG_HEBREW} "התקנת WebView2 נכשלה! התוכנה לא יכולה לפעול בלעדיו. נסו להפעיל את המתקין מחדש."
LangString webview2DownloadError ${LANG_HEBREW} "שגיאה: הורדת WebView2 נכשלה - $0"
LangString webview2DownloadSuccess ${LANG_HEBREW} "תוכנית ההתקנה של WebView2 הורדה בהצלחה"
LangString webview2Downloading ${LANG_HEBREW} "מוריד את תוכנית ההתקנה של WebView2..."
LangString webview2InstallError ${LANG_HEBREW} "שגיאה: התקנת WebView2 נכשלה עם קוד יציאה $1"
LangString webview2InstallSuccess ${LANG_HEBREW} "WebView2 הותקן בהצלחה"
LangString deleteAppData ${LANG_HEBREW} "מחיקת נתוני התוכנה (משימות, הגדרות ויומן)"
